vae_model: dvfvae

# --- paths ---
logging_dir: outputs/VAE_ACDC
data_dir:    /volatile/data/cam/ACDC/database
downsample_to_liver: true
cache_dir:   "" #/volatile/data/cam/ACDC/cache_liver
name:        DVFVAE_MM_acdc_run

# --- registration backbone ---
reg_model:              mambamorph
vm_checkpoint:          /store/usagers/p123507/MoPred/outputs/Mambamorph_ACDC/logs/07_20/16.09._mambamorph_acdc_run/mambamorph/model_best_mm.pth
mambamorph_patch_size:  2
mambamorph_freq_aware:  true
mambamorph_embed_dim: 48
reference_slices_path : 4D_MoPred_liver/mopred/data/reference_slices.csv

# --- runtime ---
gpu_idx:     "1"
num_workers: 6
seed:        123

# --- data ---
nb_inputs:   4
tp:          1
vol_size:    [32, 64, 64]  
stride:      2  

cor_pos: 16

# --- training ---
vae_epochs:  100
lr_vae:      5e-5
batch_size:  8

# Optimizer
optimizer: adamw          # choices: adam, adamw, sgd
weight_decay: 1.0e-5

# Scheduler
scheduler: plateau
plateau_factor: 0.5
plateau_patience: 3
plateau_min_lr: 1.0e-7
plateau_threshold: 1.0e-3
plateau_mode: min

# Early stopping
early_stopping_patience: 15
early_stopping_delta: 1e-3

beta_steps: 20   # ramp beta 0 → target over 20 epochs


dvfvae:
  base_channels:    16
  latent_channels:  16
  depth:            3
  beta:             1.0e-2
  lam_smooth:       0.05
  lam_ffl:          0.1
  ffl_alpha:        0.0
  horizon:          1
  use_bending:      true
  recon_loss_type:  mse    # mse | ncc
  band_low_thresh:  0.0 #0.3
  band_high_thresh: 0.0 #0.6
  lam_band_mid: 0.0 #0.1
  lam_band_high: 0.0 #1.0
  band_loss_type: energy_ratio    # pointwise | energy_ratio
